### ISSUE TITLE
Attributes on MPI windows

### ISSUE THREAD

**Issue by jsquyres** [mpiwg-rma/rma-issues#1]
Per MPI-3.1 p414 39-46, it's not clear what the Fortran datatypes are for the pre-defined attributes on MPI windows:

> In Fortran, calls to MPI_WIN_GET_ATTR(win, MPI_WIN_BASE, base, flag, ierror), MPI_WIN_GET_ATTR(win, MPI_WIN_SIZE, size, flag, ierror),
> MPI_WIN_GET_ATTR(win, MPI_WIN_DISP_UNIT, disp_unit, flag, ierror), MPI_WIN_GET_ATTR(win, MPI_WIN_CREATE_FLAVOR, create_kind, flag, ierror), and MPI_WIN_GET_ATTR(win, MPI_WIN_MODEL, memory_model, flag, ierror) will return in base, size, disp_unit, create_kind, and memory_model the (integer representation of) the base address, the size, the displacement unit of the window win, the kind of routine used to create the window, and the memory model, respectively.

Specifically: it says "integer representation of" -- does that mean INTEGER, or INTEGER(KIND=MPI_ADDRESS_KIND), or ...?

It would be good if they could be made to all be `INTEGER(KIND=MPI_ADDRESS_KIND)` so that these attributes can be like **_all**_ other (non-deprecated) Fortran attributes.  Making them be different types will force special casing in already super-complicated attribute code in MPI implementations (i.e., when reading a value, an implementation will have to special case certain keyvals and put in different read routines / instructions for them).  This feels... ugly.

Note: we have the same problem in C (because they're defined to be different types).

@hjelmn mentions to me that a simple solution might be to get rid of these attributes and have something like MPI_WIN_SHARED_QUERY defined for all windows.

This issue came up as part of open-mpi/ompi#1473.

**Comment by jeffhammond** [comment]
I support making these attributes the same type as other attributes.

Theses attributes are essential and we should not get rid of them.

Defining MPI_WIN_SHARED_QUERY for all windows is proposed in https://github.com/mpi-forum/mpi-issues/issues/23, but that has no effect on the window attributes noted above.

**Comment by hjelmn** [comment]
Well, MPI_WIN_SHARED_QUERY does take care of most of the attributes. The only ones not covered are MPI_WIN_CREATE_FLAVOR and MPI_WIN_MODEL.

**Comment by jeffhammond** [comment]
Sure, but we should not add new function calls like MPI_Win_model_query and MPI_Win_flavor_query when we already have a perfectly good solution already.  And if Fortran users can't figure out how to get the attributes directly, they can just call the C functions via `ISO_C_BINDING` wrappers.

**Comment by hjelmn** [comment]
Agreed. The benefit is the remaining attributes are just integers.

**Comment by dalcinl** [comment]
@jsquyres @jeffhammond  The proposal of using ``INTEGER(KIND=MPI_ADDRESS_KIND)`` for all attributes is IMHO wrong. It is unsymmetric with the types used in the Win create calls, and does not match the types of the C interface. I think "common sense" (from a user point of view) is more important here, this does not increase too much complexity for MPI implementations, they already have to handle different types anyway.

**Comment by jeffhammond** [comment]
In C, the output argument is a pointer to a pointer, right?  What is the equivalent in Fortran?  Is it a reference to a value or something else?

Can't we just deprecate RMA in Fortran and force everyone to use a language with a memory model?  That solves the much harder RMA Fortran issues we've discovered...

**Comment by jsquyres** [comment]
I would consider it a win if we made the types all be the same in C and all the same in Fortran. 😄

**Comment by RolfRabenseifner** [comment]
Because Section 11.2.6 (MPI-3.1 page 414) uses MPI_Win_get_attr(), it is hard to change anything without deprecating the hereby used constants MPI_WIN_BASE, MPI_WIN_SIZE, ... .
Therefore changing anything would make it only more complicated for users and implementors.
For me, it looks like that all is well defined. 
E.g., in C, MPI_Win_get_attr(MPI_WIN_DISP, &disp_unit, &flag) returns in the variable disp_unit, defined with int *disp_unit, a pointer to an integer, i.e., after the call *disp_unit is ant int with the size of the displacement unit.
In Fortran, CALL MPI_WIN_GET_ATTR(MPI_WIN_DISP, disp_unit, flag) with disp_unit defined with INTERGER(KIND=MPI_ADDRESS_KIND) disp_unit, will provide in this varable the size of the displacement unit, because on MPI-3.1 page 275 in the definition of MPI_WIN_GET_ATTR, the attribute_val is defined in Fortran as INTEGER(KIND=MPI_ADDRESS_KIND) on lines 14 and 19.

My recommendation: On MPI-3.1 page 414, in the Fortran paragraph (lines 39-46), the general wording on line 44
    "(integer representation of)"
should be changed into
    "(INTEGER (KIND=MPI_ADDRESS_KIND) representation of).

This would not be any change of the definition of the MPI API. It would be only a helpful clarification of the wording. I.e., no library or user code will be affected. If a library would be affected, then this would be a bug-fix for that library.

The usage of the attributes in C and Fortran was always asymetric and the examples in Sect.17.2.7 on pages 661-663 are helpful. Page 661, lines 40-41 clearly say that in C "address-valued" attributes are used whereas in Fortran "integer-valued" attributes are used.

**Comment by dalcinl** [comment]
@RolfRabenseifner You are definitely right, what I proposed makes not sense. I totally support your rationale and reword recommendation.

**Comment by jsquyres** [comment]
Just to be clear: @RolfRabenseifner is reminding us that all the Fortran attributes *must* be of type `INTEGER(KIND=MPI_ADDRESS_KIND)`.

He raises a point that trumps everything else: the bindings for `MPI_WIN_GET_ATTR` only allow you to pass `INTEGER(KIND=MPI_ADDRESS_KIND)`.  Fortran is more strongly typed than C -- it doesn't allow passing arbitrary types for dummy subroutine arguments.  Hence, the only possibility here is for all Fortran window attributes to be of type `INTEGER(KIND=MPI_ADDRESS_KIND)`.

**Comment by jsquyres** [comment]
RMA WG: Has there been forward progress on this?  This is two questions:

1. Should Open MPI simply "cast" (per se) the `(void*)`, `(MPI_Aint)`, and `(int)` values of `MPI_WIN_BASE`, `MPI_WIN_SIZE`, `MPI_WIN_DISP_INT`, `MPI_WIN_CREATE_FLAVOR`, and `MPI_WIN_MODEL` to `INTEGER(KIND=MPI_ADDRESS_KIND)` when reading these attributes via `MPI_WIN_GET_ATTR`?
1. If that's the case, do you need clarifying language in the text?

**Comment by jeffhammond** [comment]
I prefer that the Fortran WG decide this issue. Can you remind me what has been discussed there? Even though I'm also in the Fortran WG, I cannot remember if we have discussed this there

**Comment by jsquyres** [comment]
I believe that @RolfRabenseifner provided the Fortran WG smackdown here on this ticket.  😄 

The issue is that the RMA WG created attributes that are different types in C (contrary to the rest of the MPI spec).  With C's `(void*)`, this is fine.  But the Fortran ATTR_GET functions can *only* retrieve an `INTEGER(KIND=MPI_ADDRESS_KIND)`.  There's slightly weak language in the RMA text saying that it should write the "integer representation of" these values to the output Fortran parameter. Is this deemed "good enough", or does there need to be clarification language?

**Comment by jeffhammond** [comment]
@jsquyres I think the text is good enough, but I would not object to an improvement.  Personally, I think that @RolfRabenseifner's proposal of "(INTEGER (KIND=MPI_ADDRESS_KIND) representation of)" is gross, as it is clear that this is the type from the signature, and the current text saying the "integer representation" ensures that users understand how addresses will be interpreted.

**Comment by jsquyres** [comment]
FWIW, this came up as part of testing the Open MPI RMA implementation (i.e., the RMA attributes). 😄

**Comment by wgropp** [comment]
I also think that this text is good enough, and our test suite works with this.

Bill

William Gropp
Director, Parallel Computing Institute
Thomas M. Siebel Chair in Computer Science
Chief Scientist, NCSA
University of Illinois Urbana-Champaign

**Comment by jeffhammond** [comment]
This appears to be resolved.
