### ISSUE TITLE
MPI 4.0 Chapter Committee Ratification Steps

### ISSUE THREAD

**Issue by devreal** [mpiwg-rma/rma-issues#15]
I looked through the changes to the RMA chapter between 3.1 and 4.0 (using Github, as per https://github.com/mpi-forum/mpi-standard/compare/mpi-3.x...mpi-4.x#diff-abcde0810b89c0faf160df24683574bc0f017a2e677e3b8dd0d2d73116877a9e)

I didn't find any issues in the changes between 3.1 and 4.0. I did find a minor formatting issue: I believe the `\mpiarg{z}` in this line https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-one-side/one-side-2.tex#L4459 should be ~`\const{z}`~ `\code{z}` to match what is used later in the document for local variables, e.g., https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-one-side/one-side-2.tex#L4472. The way the examples are written,`z` is a local variable that is assigned the result of an MPI operation so `z` should be set as normal code. Do people have other opinions on that?

Here is a list of changes between MPI 3.1 and 4.0 for the RMA chapter I could find:

1) Pythonization / Embiggenment
2) Formatting changes for consistency with the document standards  (use of `\mpicode`, `\infokey`, `\ctype`)
3) Added info key to request specific memory alignment for `MPI_Win_allocate` and `MPI_Win_allocate_shared`
4) `\MPI/ exception` -> `error` (https://github.com/mpi-forum/mpi-standard/compare/mpi-3.x...mpi-4.x#diff-abcde0810b89c0faf160df24683574bc0f017a2e677e3b8dd0d2d73116877a9eL1253)
5) Status field semantics consistency to match other places of the document (https://github.com/mpi-forum/mpi-standard/compare/mpi-3.x...mpi-4.x#diff-abcde0810b89c0faf160df24683574bc0f017a2e677e3b8dd0d2d73116877a9eL1805)
6) Added some index items (e.g., https://github.com/mpi-forum/mpi-standard/compare/mpi-3.x...mpi-4.x#diff-abcde0810b89c0faf160df24683574bc0f017a2e677e3b8dd0d2d73116877a9eR2784)
7) Formatting: `bit-vector OR` -> `bit vector \mpicode{OR}`

Anything missing?

**Comment by wgropp** [comment]
\const should only be used for MPI constants (and that are not datatypes, error codes/classes, or strings). \mpicode should be used for language independent code, \code for C or Fortran examples. \mpiarg should be used for parameter names used in the routine definitions.

**Comment by devreal** [comment]
Ahh, what I meant was `\code`, not `\const`...

**Comment by devreal** [comment]
MPI 4.0 has been ratified, closing.
