### ISSUE TITLE
Clarify that MPI_Window objects must be freed before MPI_Finalize

### ISSUE THREAD

**Issue by csubich** [mpiwg-rma/rma-issues#27]
Greetings,

Recently, I was [surprised](https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/MPI-Finalize-errors-unless-MPI-Win-Free-is-called/m-p/1477606/thread-id/10548#M10596) by an error at `MPI_Finalize` on Intel's MPI implementation (MPICH-based, I think) with the following code:

```fortran
program test_window
   !! Test whether MPI dies when a window is created but not freed before MPI_Finalize
   use mpi_f08
   use, intrinsic :: iso_fortran_env
   use, intrinsic :: iso_c_binding
   integer, dimension(10) :: window_array
   integer :: myrank, numproc
   type(MPI_Win) :: created_window
   call MPI_Init()
   call MPI_Comm_size(MPI_COMM_WORLD,numproc)
   call MPI_Comm_Rank(MPI_COMM_WORLD,myrank)
   write(0,'("Rank ",I0,"/",I0," initialized")') myrank+1, numproc
   call MPI_Win_Create(window_array, int(10,kind=MPI_ADDRESS_KIND), &
                       1, MPI_INFO_NULL, MPI_COMM_WORLD, created_window)
   write(0,'("Rank ",I0," created window")') myrank+1
   call MPI_Finalize()
   write(0,'(" Rank ",I0," finalized")') myrank+1
end program
```

The error was evidently mine, for not freeing the `MPI_Win` object before the call to `MPI_Finalize`.  After some long discussion in the above-linked Intel thread, I've convinced myself that the specification does allow implementations to treat this as an error, making the call to `MPI_Win_free` obligatory.

However, this requirement does not appear to be obvious.  The language around `MPI_Finalize` refers to completing communications, and my mental model of an `MPI_Win` object was that it was more like a communicator object (which does not need to be explicitly freed) than a request (which must be completed).

Might a future version of the MPI specification highlight this requirement more explicitly?

**Comment by jeffhammond** [comment]
First, I don't care whether your program is strictly compliant or not - Intel MPI should not crash like that.  They have all the necessary information to clean up windows during finalization and not crash.  MPICH built with the necessary debug options will report every single handle that's still active during finalize, so the infrastructure is already there inside of Intel MPI.

Second, I have yet to find anything in the standard that says your program is wrong, but I'll wait until others have weighed in to take a strong position here.

Here's what I found so far:

§ 11.2.2

> Before an MPI process invokes MPI_FINALIZE, the process must perform all MPI calls needed to complete its involvement in MPI communications associated with the World Model. It must locally complete all MPI operations that it initiated and must execute matching calls needed to complete MPI communications initiated by other processes.

> The call to MPI_FINALIZE does not free objects created by MPI calls; these objects are freed using MPI_XXX_FREE calls.

This does not state that windows must freed, only that finalize doesn't free them.  It says you must complete all communication, but you haven't initiated any in your example program.

A future version of the standard should clarify this situation for all objects.

**Comment by jeffhammond** [comment]
Can you please recreate this issue under https://github.com/mpi-forum/mpi-issues/issues?  It is more general than RMA and should be looked at by more people.  Thanks!

**Comment by jeffhammond** [comment]
Closing this in favor of https://github.com/mpi-forum/mpi-issues/issues/711
